### ISSUE TITLE
Enabling / Disabling Knife Rounds on Match Page

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#80] opened 2019-05-27 15:41 UTC
Hi @PhlexPlexico,

Great work! 

It would be good if we can have match setup like 1on1 and workshop maps on web panel.

Also the option of enabling/disabling knife round.

**Comment by PhlexPlexico** [comment] 2019-05-27 16:15
Thanks!

I believe workshop maps can be taken care of if you include it in the config file. For 1v1s, since from what I see that get5 doesn't really support it, I probably won't make that change. 

Enabling/disabling knife round is a great idea. I swear it was in there, but never really had a use for it. I'll look into that after I fix the coaches showing up on the stat boards.

**Comment by PhlexPlexico** [comment] 2019-05-30 05:41
Latest development build should now! Please feel free to test at http://get5.phlexplexi.co if you don't have an environment up and running.

**Comment by xe1os** [comment] 2019-05-30 12:06
@PhlexPlexico  kudos! Thank you for the efforts. It works :)

**Comment by PhlexPlexico** [comment] 2019-05-31 14:23
If it's confirmed working, I'm going to close this now. Any problems arise, feel free to create a new issue!

**Closed by PhlexPlexico** 2019-05-31 14:23 UTC
Labels: enhancement
