### ISSUE TITLE
[BUG] Team leaderbords

### ISSUE THREAD

**Issue by MikkelDK** [PhlexPlexico/get5-web#155] opened 2019-10-22 17:11 UTC
**Describe the bug**
Problems with view "/leaderboard" (Team Leaderboards)

**Which Build**
master

**To Reproduce**
1. Go to 'http://get5.lindhost.eu/'
2. Click on 'Leaderboards'
3. And click 'Team Leaderboard'
4. See error: `Sorry, unexpected error: 'NoneType' object has no attribute 'id'`

**Expected behavior**
After the update of the new build, for fix "Admin" can't see stats on the private match?

**Additional context**´
Error log:
```
[2019-10-22 19:08:52,634] {/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py:1753} ERROR - Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/get5-web/get5/leaderboard.py", line 126, in leaderboard
    return getLeaderboard()
  File "/var/www/get5-web/get5/leaderboard.py", line 56, in getLeaderboard
    dTeamStandings[winningTeam.name]['teamid'] = winningTeam.id
AttributeError: 'NoneType' object has no attribute 'id'
[2019-10-22 19:08:52,635] {/var/www/get5-web/get5/__init__.py:174} ERROR - 'NoneType' object has no attribute 'id'
```

**Comment by PhlexPlexico** [comment] 2019-10-22 17:24
Duplicate of issue #145. Closing and refer to that one. Thanks!

**Closed by PhlexPlexico** 2019-10-22 17:24 UTC
Labels: bug
