### ISSUE TITLE
[BUG] Users can't see "Total Matches" on Seasons

### ISSUE THREAD

**Issue by MikkelDK** [PhlexPlexico/get5-web#166] opened 2019-10-27 18:23 UTC
Hi,

Some users can't see "Total Matches" on Seasons.

If I'm logged out of the get5page. I can see it, but others can't.

What can I do?
I can't find any errors.

Here; the user can't see "Total Matches"
![screen1](https://i.gyazo.com/41d0dbc079fe551442d999adb00e4e6c.png)

User can see them if **He clicking on Week 1**
![screen2](https://i.gyazo.com/26ae5f84eeb4f7342f4d9c2506918c13.png)

I did tell the user to try, logout. - He can't see the "Total Matches" (Where it should show: **12** - but it displays: **0**)
![screen3](https://i.gyazo.com/98f05ff5ac5ab4e5fb0dc6b5b8ab3e58.png)

Here, he did log on, but can't see it.
![screen4](https://i.gyazo.com/e88a395fe55e2f7ec12564836a9f026d.png)

**Comment by PhlexPlexico** [comment] 2019-10-27 20:07
I believe it's a bug in the template. I need to look into it more, but from what I can see, the map function isn't working as intended.

Possible error line: [here](https://github.com/PhlexPlexico/get5-web/blob/development/get5/templates/seasons.html#L45)

In your get5 instance, would you mind putting this line right below line 46 in `season.py`
```python
app.logger.info("Our total matches are: {}".format(seasoned_matches))
```
Restart your Apache instance, and then tell the user to navigate to the page again. And provide the output from the log. And also once when you check the page as well. I need to verify it's just in the template, and not the middleware itself.

Thanks!

**Comment by PhlexPlexico** [comment] 2019-10-27 20:08
Wait, nevermind. I think I know where the problem is. Let me push out a quick fix.

**Comment by PhlexPlexico** [comment] 2019-10-27 20:10
https://github.com/PhlexPlexico/get5-web/commit/e82249bc2736cf843aea2fb1198fac2ec3a83ed4 Should fix.

**Comment by MikkelDK** [comment] 2019-10-27 20:32
@PhlexPlexico danke <3

**Comment by PhlexPlexico** [comment] 2019-10-27 20:46
Works now?

**Comment by MikkelDK** [comment] 2019-10-27 20:57
@PhlexPlexico Yes! ;)

**Comment by PhlexPlexico** [comment] 2019-10-27 21:18
Perfect. Going to close this issue now since that seems to have done it. Thanks for the report! 👍

**Closed by PhlexPlexico** 2019-10-27 21:18 UTC
Labels: bug
