### ISSUE TITLE
[BUG] Error in Team Leaderboard URL

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#145] opened 2019-10-15 10:05 UTC
**Describe the bug**
Error while viewing Team Leaderboard (/leaderboard)

**Which Build**
Both

**To Reproduce**
1. Go to 'Leaderboards'
2. Click on 'Team Leaderboard'
3. See error 'Sorry, unexpected error: 'NoneType' object has no attribute 'id'

**Expected behavior**
Should show the team leaderboard for all matches irrespective of season.

**Additional context**
We should be able to see top team across all matches, like we have player leaderboard for all matches (/leaderboard/players)

**Comment by PhlexPlexico** [comment] 2019-10-15 13:54
This is most likely do to an error in your data, as seen in issue #134. Please provide a log file when the issue currently happens, as it is far easier to debug. Thanks!

**Comment by xe1os** [comment] 2019-10-16 10:36
> This is most likely do to an error in your data, as seen in issue #134. Please provide a log file when the issue currently happens, as it is far easier to debug. Thanks!

[get5.log](https://github.com/PhlexPlexico/get5-web/files/3733794/get5.log)

[get5.log.2019-10-14.log](https://github.com/PhlexPlexico/get5-web/files/3733796/get5.log.2019-10-14.log)

@PhlexPlexico thank you

**Comment by PhlexPlexico** [comment] 2019-10-16 13:47
You currently have matches that are cancelled, or a match that has been completed with no winner.
`dTeamStandings[winningTeam.name]['teamid'] = winningTeam.id
AttributeError: 'NoneType' object has no attribute 'id'`

Please run `select * from \`match\` where winner is NULL` and update those records accordingly.

**Comment by xe1os** [comment] 2019-10-22 12:07
> You currently have matches that are cancelled, or a match that has been completed with no winner.
> `dTeamStandings[winningTeam.name]['teamid'] = winningTeam.id AttributeError: 'NoneType' object has no attribute 'id'`
> 
> Please run `` select * from `match` where winner is NULL `` and update those records accordingly.

@PhlexPlexico i have updated the records with NULL information in the database using your query `` select * from `match` where winner is NULL ``.

Still getting the same error :(

**Comment by PhlexPlexico** [comment] 2019-10-22 13:31
Can you post your latest log again after causing this error? It seems you have some data problems in your database that's causing this error, as I cannot reproduce.

**Comment by PhlexPlexico** [comment] 2019-10-22 17:28
Also, would you mind running `select * from map_stats where winner is NULL`? It's possible the winners were never set in the map stats.

**Comment by MikkelDK** [comment] 2019-10-22 17:33
Aha. it's because, if you are setting "forfeit" to the team (without connecting to gameserver e.g) it will say that.

Example from my database:
![screen](https://i.gyazo.com/9173200d890fb5bacb6e16ac6ff86016.png)

**Comment by PhlexPlexico** [comment] 2019-10-22 17:34
Uno momento, making one fix for this as well within the query.

**Comment by PhlexPlexico** [comment] 2019-10-22 17:38
https://github.com/PhlexPlexico/get5-web/commit/6ece3048287c4240693ebdb7f0aa6cfa42286b57 Should fix that now.

**Comment by MikkelDK** [comment] 2019-10-22 20:12
> [6ece304](https://github.com/PhlexPlexico/get5-web/commit/6ece3048287c4240693ebdb7f0aa6cfa42286b57) Should fix that now.

I can confirm it works! ;) /close this =D

**Comment by PhlexPlexico** [comment] 2019-10-23 02:12
Latest push to master will also show winner in the map stats as well.

**Closed by PhlexPlexico** 2019-10-23 02:12 UTC
Labels: bug
