### ISSUE TITLE
[BUG] Team not getting assigned properly

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#125] opened 2019-08-23 05:10 UTC
**Describe the bug**
I created 2 teams on my panel and created a match of BO3 . After every player joining the server and the veto begins and 3 maps are selected 
eg. 
Team 1 picks _Dust2_
Team 2 select CT side
Team 2 picks _Mirage_
Team 1 select CT Side
Last map remaining _Inferno_

TandelK  - Team1
Bot2 - Team 2

After the map has been loaded Team 2 gets in CT but the Team 2 name will be Team 1 name as well as player Tags will have Team 1 Tags. 

Bot2 player will have Team 1 Tags and even on the panel it will show Team 1 and inside the player name will be of Bot2. 

The scores get registered in the similar way. Team1 bascially won the match but the team name of Team 1 is of Team 2 i.e. Bot2 so the game 1 match is won by Bot2.

Map Changed. 

Now its get normal. Team 1 has Team 1 players and Team 2 has team 2 players. But the first match is won by Team 2 as per the database and again if Team 1 won the match becomes automatically tie . 

**Which Build**
Master

**To Reproduce**
Download Master branch and deploy it . Use the get5_apistats.smx of release section 
Create a match with 2 team  of BO3 and start the game. See the issue as mentioned above. 

**Expected behavior**
Team 1 should go to normally Team 1 section .

**Comment by TandelK** [comment] 2019-08-23 05:12
@PhlexPlexico Currently i dont have internet access to the panel outside of my network. It is deployed on WSL Ubuntu system. Once i can deploy on any public domain i can give you even links of them once deployed. 

I had no issues with the plugin you told to download from.

Also Phlex if possible can you join back the Discord Server ?

**Comment by PhlexPlexico** [comment] 2019-08-23 05:23
I know exactly what this has to do with, and it's the enforcement of teams. Right now a workaround is to create one match on a server, cancel it, and resume it again with enforced teams. This should allow the teams to sort themselves out again. For some reason, the cvar does not play as nicely as intended, and I think I may end up removing the enforce teams from it, since it just doesn't work. I'll look in to see what I can do about it, but the config from `get5` will just override it, and it's my fault for trying to interface with get5 directly.

So yeah, workaround for now will be to be create one match with enforced teams, cancel it, and start it again. I'll remove the enforce teams as soon as I can here.

As for discord, I really don't like spreading out the information I post with this page, as I tend to get scatterbrained fairly easily, and distracted with other problems when I intend to focus on one. Just post a link here and I'll rejoin when I have the capacity to help out otherwise. If there's any problems or suggestions, you're better off posting here for a quicker reply :)

**Comment by PhlexPlexico** [comment] 2019-08-26 13:56
So anymore issues with this?

**Comment by TandelK** [comment] 2019-08-27 05:16
Still i have not yet fully checked if the isssue . I will update it once i am able to replicate .

**Comment by PhlexPlexico** [comment] 2019-08-31 23:00
Possibly not due to webpanel, but how get5 handles the `get5_check_auths` functionality. A buddy of mine tried setting the value to 1 in the creation, with the server set to 0. After vetoes and map change, users could not connect because they were not team players in the match. 

That being said, I'm going to implement a possible work-around, and have the server change maps after receiving the config, so it should force whatever value is given from the JSON config.

**Comment by PhlexPlexico** [comment] 2019-09-03 01:26
Okay, the map change effect is now in place for enforcing teams. This should not cause anymore problems with the teams not being sorted/on the wrong team. Lemme know if this works just fine now.

**Comment by TandelK** [comment] 2019-09-03 06:57
Ok will update you once i finish checking it up.

**Comment by PhlexPlexico** [comment] 2019-09-19 03:55
Going to close this issue as there hasn't been anything heard back for in two weeks.

**Closed by PhlexPlexico** 2019-09-19 03:55 UTC
Labels: bug, on hold
