### ISSUE TITLE
[BUG] [get5.smx] Failed to load match config: Steamworks GET request failed, HTTP status code = 0

### ISSUE THREAD

**Issue by tuudik** [PhlexPlexico/get5-web#154] opened 2019-10-22 14:02 UTC
**Describe the bug**
After making the match in web, the match is not "sent" to server

**Which Build**
master

**To Reproduce**
1. Make match
2. Checking console
3. Error appears: [get5.smx] Failed to load match config: Steamworks GET request failed, HTTP status code = 0

**Expected behavior**
match is loaded to the server

**Additional context**
I also tried to load the config manually with get5_loadmatch_url command, but the result was same.

**Comment by MikkelDK** [comment] 2019-10-22 14:04
Are you using https? SteamWorks don't support HTTPS ;)

**Comment by PhlexPlexico** [comment] 2019-10-22 14:22
This is more of a get5 problem. It's been reported several times on that repo. Would you mind trying some of the solutions there?

**Comment by tuudik** [comment] 2019-10-22 14:33
Could someone whos setup works, give me list of plugins and extensions and
versions so i could do some comparsion:(?

T, 22. oktoober 2019 kell 17:22 PhlexPlexico <notifications@github.com>
kirjutas:

**Comment by PhlexPlexico** [comment] 2019-10-22 14:39
![image](https://user-images.githubusercontent.com/3514085/67297615-61db7980-f4a7-11e9-8868-04d2927d0419.png)
This is all I'm running on most of my servers. Are you using an actual hostname and not a server IP?

**Comment by tuudik** [comment] 2019-10-22 16:09
I am using hostname, and it resolves perfectly when i try with curl.

**Comment by PhlexPlexico** [comment] 2019-10-22 16:13
What version of get5 are you using?

**Comment by tuudik** [comment] 2019-10-22 16:15
```
sm plugins list
[SM] Listing 20 plugins:
  01 "Admin File Reader" (1.9.0.6282) by AlliedModders LLC
  02 "Reserved Slots" (1.9.0.6282) by AlliedModders LLC
  03 "Get5" (0.7.2-dev+471) by splewis
  04 "Client Preferences" (1.9.0.6282) by AlliedModders LLC
  05 "Admin Menu" (1.9.0.6282) by AlliedModders LLC
  06 "Basic Chat" (1.9.0.6282) by AlliedModders LLC
  07 "Basic Info Triggers" (1.9.0.6282) by AlliedModders LLC
  08 "Basic Comm Control" (1.9.0.6282) by AlliedModders LLC
  09 "Fun Commands" (1.9.0.6282) by AlliedModders LLC
  10 "Sound Commands" (1.9.0.6282) by AlliedModders LLC
  11 "RankMe" (3.0.3.Kento.31.3) by lok1, Scooby, Kento, pracc, Kxnrl, CrazyHackGUT
  12 "Basic Votes" (1.9.0.6282) by AlliedModders LLC
  13 "Fun Votes" (1.9.0.6282) by AlliedModders LLC
  14 "Basic Ban Commands" (1.9.0.6282) by AlliedModders LLC
  15 "Admin Help" (1.9.0.6282) by AlliedModders LLC
  16 "Basic Commands" (1.9.0.6282) by AlliedModders LLC
  17 "Player Commands" (1.9.0.6282) by AlliedModders LLC
  18 "Anti-Flood" (1.9.0.6282) by AlliedModders LLC
  19 "Get5 Web API Integration" (0.7.2-dev+471) by splewis
  20 "CS:GO PugSetup" (2.0.6-dev+488) by splewis
sm exts list
[SM] Displaying 11 extensions:
[01] Automatic Updater (1.9.0.6282): Updates SourceMod gamedata files
[02] Webternet (1.9.0.6282): Extension for interacting with URLs
[03] CS Tools (1.9.0.6282): CS extended functionality
[04] BinTools (1.9.0.6282): Low-level C/C++ Calling API
[05] SDK Tools (1.9.0.6282): Source SDK Tools
[06] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
[07] Client Preferences (1.9.0.6282): Saves client preference settings
[08] SQLite (1.9.0.6282): SQLite Driver
[09] Top Menus (1.9.0.6282): Creates sorted nested menus
[10] GeoIP (1.9.0.6282): Geographical IP information
[11] MySQL-DBI (1.9.0.6282): MySQL driver implementation for DBI
```

**Comment by PhlexPlexico** [comment] 2019-10-22 16:18
If you're using this webpanel, please use the supplied api integration that is in the releases tab of this repository. There was changes made to the plugin to enhance functionality with this project.

**Comment by tuudik** [comment] 2019-10-22 16:23
Do you mean this one?
https://github.com/PhlexPlexico/get5-web/releases/download/0.5/get5_apistats.smx

Do you think it will also resolve my issue?

**Comment by MikkelDK** [comment] 2019-10-22 16:24
> Do you mean this one?
> https://github.com/PhlexPlexico/get5-web/releases/download/0.5/get5_apistats.smx
> 
> Do you think it will also resolve my issue?

You need to use it if you are using Phlex's Get5panel! ;)

**Comment by PhlexPlexico** [comment] 2019-10-22 16:25
I sure hope so. If not, it's a setup issue with your server. The failure for steamworks usually means something on your server is possibly configured incorrectly (i.e. your web server always redirects to HTTPS, which, if done by letsencrypt, will do that). Otherwise it could be an install issue.

**Comment by PhlexPlexico** [comment] 2019-10-22 16:26
Also as you can see by the plugin, it's a get5 error, and less of a webpanel error, too. If those suggestions don't fix it, I highly recommend creating an issue at the right repo as there are more knowledgeable people than me that know of this issue :)

**Comment by TandelK** [comment] 2019-10-23 05:29
@PhlexPlexico there is a problem with your apistats . If we download Compiled plugin from releases section it works perfectly but if we compile the plugin by ourself it gives us error while creating match. @MikkelDK also faced the same issue

**Comment by PhlexPlexico** [comment] 2019-10-23 05:46
That's why there's a releases section :) 

I have an environment I just setup for this - which requires System2 and sm-json-v1.2 to be present. I'm unsure as to why your environment fails to compile it, and is it working with the latest release now?

Are you able to produce the stack trace of the problem? Can you show at what point it fails in get5_apistats.smx and not get5.smx? This would be immensely helpful for debugging. If I can't see why it's failing, I can't help. The provided log in the top comment of this issue is showing get5.smx failing, which isn't this plugin, and I need the full stack trace. If you can provide me that, I can help.

**Comment by tuudik** [comment] 2019-10-23 16:11
I got it resolved. First the manual get_loadmatch_url failed because i had http:// in front of the url.
And the main reason why match was not sent to server was because i had parameter:
`TESTING = True`

After changing it to False, everything worked like a charm:)

**Comment by PhlexPlexico** [comment] 2019-10-23 16:12
Glad to hear everything is working as intended then! I'm going to close this issue now, and if there's any more troubles that wasn't discussed here, feel free to open another ticket. I'll get the new plugin updated as soon as I possibly can for the releases section. Thank you!

**Closed by PhlexPlexico** 2019-10-23 16:12 UTC
Labels: bug, on hold
